const greetings =[
"Hi there! Let's cook up something amazing together!",
"Hello! Excited to help you find the perfect recipe.",
"Welcome! How can I assist you with your cooking today?",
"Hey! Let's explore some mouthwatering recipes.",
"Greetings! Let's get cooking with Twin Chef.",
"Hi! I'm here to help you find recipes that match your ingredients.",
"Hello there! Ready to dive into the world of culinary delights?",
"Welcome to Twin Chef! Let's cook up a storm.",
"Hey there! Let's find some recipes you'll love.",
"Hello! Ready to explore tasty recipes with me?",
"Hi! I'm your cooking assistant. What's on the menu today?",
"Greetings! Let's whip up some delicious dishes together.",
"Welcome to Twin Chef! What ingredients do you have?",
"Hi there! Let's find some recipes that suit your taste.",
"Hello! Excited to help you create culinary masterpieces.",
"Hey! Let's discover new flavors and recipes together.",
"Welcome! Let's find recipes that match your ingredients.",
"Hi! Ready to embark on a culinary adventure?",
"Hello! Let's cook something wonderful today.",
"Greetings! I'm here to help you with your cooking journey.",
"Hi there! Let's find the perfect recipe for you.",
"Welcome to Twin Chef! What can I help you cook today?",
"Hey! Let's explore some amazing recipes together.",
"Hello! I'm excited to assist you with your culinary endeavors.",
"Hi! Let's discover some delicious recipes.",
"Greetings! Ready to discover new tastes and flavors?",
"Welcome! Let's cook up some magic in the kitchen.",
"Hi there! Let's make cooking easy and fun.",
"Hello! Let's find the perfect recipe for your ingredients.",
"Hey! Excited to help you find recipes you'll love.",
"Welcome to Twin Chef! What dish are you craving today?",
"Hi! Let's create delicious memories with great recipes.",
"Hello! Ready to find recipes that match your style?",
"Greetings! Let's explore the world of culinary delights.",
"Hi there! Let's find recipes that inspire you.",
"Welcome! Let's cook something special together.",
"Hey! Let's make cooking simpler and more enjoyable.",
"Hello! Let's find the best recipes for your ingredients.",
"Hi! Ready to explore a world of tasty possibilities?",
"Greetings! Let's create something delicious today.",
"Welcome to Twin Chef! Let's find recipes tailored for you.",
"Hi there! Let's uncover recipes that match your preferences.",
"Hello! Let's make cooking easier with great recipes.",
"Hey! Ready to discover new flavors and recipes?",
"Welcome! Let's find recipes that fit your taste.",
"Hi! Let's cook up something amazing together.",
"Hello! Excited to help you find the perfect recipe.",
"Greetings! I'm here to assist you with your cooking journey.",
"Hi there! Let's explore some delicious recipes.",
"Welcome to Twin Chef! What can I help you cook today?",
"Hey! Let's find recipes that match your ingredients.",
"Hello! Let's cook something wonderful today.",
"Hi there! Let's make cooking easy and enjoyable.",
"Greetings! Let's explore the world of culinary delights.",
"Hello! I'm your cooking assistant. What's on the menu today?",
"Hey! Let's discover new flavors and recipes together.",
"Welcome! Let's find recipes that match your ingredients.",
"Hi there! Let's cook up a storm in the kitchen.",
"Hello! Ready to embark on a culinary adventure?",
"Greetings! Let's whip up some delicious dishes together.",
"Hi! I'm here to help you find recipes that suit your taste.",
"Hey! Let's explore some mouthwatering recipes.",
"Welcome to Twin Chef! Let's cook something amazing.",
"Hello! Let's find the perfect recipe for your ingredients.",
"Hi! Ready to discover new tastes and flavors?",
"Greetings! Let's create something delicious today.",
"Hey there! Let's make cooking simpler and more fun.",
"Welcome! Let's cook up a feast together.",
"Hi! Let's find recipes that inspire your culinary creativity.",
"Hello! Excited to assist you with your cooking endeavors.",
"Hey! Let's uncover recipes you'll love cooking.",
"Welcome to Twin Chef! Let's make cooking enjoyable.",
"Hi there! Let's explore the world of tasty recipes.",
"Hello! Ready to find recipes that match your style?",
"Greetings! Let's cook something special today.",
"Hi! Let's create delicious dishes with great recipes.",
"Hey! Let's find recipes that fit your culinary preferences.",
"Welcome! Let's make cooking easier and more fun.",
"Hello! Let's cook up some magic in the kitchen.",
"Hi there! Let's find recipes that suit your taste buds.",
"Greetings! I'm your cooking assistant. What's cooking?",
"Hey! Let's explore new flavors and cooking techniques.",
"Welcome to Twin Chef! Let's discover tasty recipes.",
"Hi! Let's cook something delicious together.",
"Hello! Excited to help you with your cooking journey.",
"Hey there! Let's find the perfect recipe for you.",
"Greetings! Ready to create culinary masterpieces?",
"Hi! Let's make cooking fun and enjoyable.",
"Hello! Let's uncover recipes that match your preferences.",
"Hey! Let's find recipes that inspire your culinary creativity.",
"Welcome! Let's cook something amazing today.",
"Hi there! Let's explore delicious recipes together.",
"Hello! Ready to find recipes that suit your style?",
"Greetings! Let's cook up some tasty dishes.",
"Hi! Let's make cooking an adventure.",
"Hey! Let's discover new recipes you'll love.",
"Welcome! Let's find recipes that match your ingredients.",
"Hello! Excited to help you with your cooking journey.",
"Hi there! Let's cook up a storm in the kitchen.",
"Hi! Ready to create mouthwatering dishes together?",
"Hello! Let's dive into some amazing recipes.",
"Welcome to Twin Chef! What delicious meal can I help you cook today?",
"Hey there! Excited to explore new recipes with you.",
"Greetings! Let's find some culinary gems together.",
"Hi! Let's embark on a tasty culinary journey.",
"Hello! Ready to whip up some fantastic recipes?",
"Welcome! Let's make cooking a delightful experience.",
"Hey! Let's discover recipes that suit your palate.",
"Greetings! I'm here to help you find the best recipes.",
"Hi there! Let's cook something extraordinary today.",
"Hello! Ready to explore a world of flavors?",
"Welcome to Twin Chef! What recipe are you craving?",
"Hey! Let's create culinary masterpieces together.",
"Hi! Let's find recipes that will amaze your taste buds.",
"Hello! Excited to help you with your cooking adventures.",
"Greetings! Let's cook up some magic in the kitchen.",
"Hi there! Let's make cooking fun and easy.",
"Welcome! Let's find recipes that match your cravings.",
"Hey! Ready to explore new and exciting recipes?",
"Hello! Let's make cooking a fun and enjoyable experience.",
"Hi! Let's discover new recipes together.",
"Greetings! I'm here to assist you with all your cooking needs.",
"Hi there! Let's find recipes that will delight you.",
"Hello! Ready to cook up something delicious?",
"Welcome to Twin Chef! Let's find recipes you'll love.",
"Hey! Let's explore a variety of delicious recipes.",
"Hi! Let's create tasty dishes with simple ingredients.",
"Greetings! Ready to discover amazing recipes?",
"Hello! Let's make cooking an enjoyable adventure.",
"Hi there! Let's cook up something fantastic today.",
"Welcome! Let's explore recipes that inspire you.",
"Hey! Let's find the perfect recipe for your ingredients.",
"Greetings! Let's whip up some mouthwatering dishes.",
"Hi! Ready to explore a world of delicious recipes?",
"Hello! Let's cook something special together.",
"Welcome to Twin Chef! What can I help you cook today?",
"Hey! Let's make cooking easy and enjoyable.",
"Hi! Let's discover recipes that fit your style.",
"Greetings! I'm here to help you on your culinary journey.",
"Hi there! Let's find recipes that inspire your cooking.",
"Hello! Ready to uncover some amazing recipes?",
"Welcome! Let's make cooking a fun experience.",
"Hey! Let's create culinary delights together.",
"Hi! Let's find the perfect recipe for your meal.",
"Greetings! Ready to cook up a storm in the kitchen?",
"Hello! Let's explore the world of tasty recipes.",
"Hi there! Let's make cooking simple and fun.",
"Welcome to Twin Chef! What delicious dish can I help you with today?",
"Hey! Let's find recipes that match your culinary preferences.",
"Hi! Ready to create some culinary magic?",
"Hello! Let's discover fantastic flavors together.",
"Welcome! Let's make cooking an enjoyable adventure.",
"Hey there! Let's explore recipes that excite your taste buds.",
"Greetings! I'm thrilled to help you find the best recipes.",
"Hi! Let's embark on a delightful culinary journey.",
"Hello! Ready to whip up some tasty dishes?",
"Welcome! Let's make cooking a delightful experience.",
"Hey! Let's find recipes that suit your taste.",
"Greetings! Let's cook something extraordinary together.",
"Hi there! Ready to create culinary masterpieces?",
"Hello! Let's dive into a world of delicious flavors.",
"Welcome to Twin Chef! What recipe can I assist you with today?",
"Hey! Let's make cooking fun and enjoyable.",
"Hi! Let's find recipes that will satisfy your cravings.",
"Hello! Excited to help you in your cooking endeavors.",
"Greetings! Let's create something delicious in the kitchen.",
"Hi there! Let's make cooking an exciting experience.",
"Welcome! Let's explore recipes that match your desires.",
"Hey! Ready to discover some incredible recipes?",
"Hello! Let's make cooking an easy and fun activity.",
"Hi! Let's find new recipes to try together.",
"Greetings! I'm here to assist with all your cooking needs.",
"Hi there! Let's find recipes that will delight your palate.",
"Hello! Ready to cook up something wonderful?",
"Welcome to Twin Chef! Let's find recipes that you'll love.",
"Hey! Let's explore a world of culinary possibilities.",
"Hi! Let's create delicious dishes with simple ingredients.",
"Greetings! Ready to discover some tasty"

];

export default greetings;
